language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "6"
  - "8"
  - "9"
before_script:
  - npm prune
install:
  - npm install
script:
  - npm tun ci:validate
  - npm run test
after_success:
  - npm run ci:github-release
